### ISSUE TITLE
CodeBlock in `py` ?

### ISSUE THREAD

**Issue by arthurhjorth** [qiemem/PythonExtension#4]
Would it be nice or not to use the `CodeBlock` datatype in the py extension? I can't tell. It would look neater like this:

```
py:run [
    # here is some code
    # and more code here
]
```

compared to

```
(py:run 
    "set foo bar"
    "set baz qux"
)
```

`CodeBlock` also already allows us to inject variables, right? So we could do

```
(py:run [ foo -> 
    set bar foo
] baz) 
```

**Comment by qiemem** [comment]
Already discussed in chat, but unfortunately, code blocks won't work for a number of reasons:

1. Code blocks don't include newlines, which Python needs.
2. The compiler just has a list of tokens at that point (no newline info), so creating an improved code block would be hard.
3. The netlogo indenter won't play nice with Python code. Better to just manually format things than to constantly fight it.

RE arguments: doing that with code blocks (as in LS) just involves interpreting them as strings, and then recompiling them as anonymous procedures, so doesn't apply here. That said, we *could* do it with the current implementation, with something like:

```
(py:run
   "[ foo bar ] ->"
   "plt.plot(foo, bar)"
)
```

or something. But that's kinda gross, a pain to implement correctly, and bound to have weird edge cases where it doesn't do what you want. `py:set` is also easy enough to use that having something complicated like this is unnecessarily asking for trouble.

For anyone who happens upon this issue, a good alternative to writing big blocks of Python in NetLogo is to just write a Python script with those big blocks contained in functions. Then, import that script into your model, and just call the functions.
