### ISSUE TITLE
PythonExtension in MacOS does not work

### ISSUE THREAD

**Issue by terna** [qiemem/PythonExtension#9]
I've created the folder py in extensions with pyext.py and py.jar in it.

In NetLogo code I've simply:
extensions [py]
Moving to Interface, immediately I received the error reported in the attached error.txt file.
[error.txt](https://github.com/qiemem/PythonExtension/files/1779082/error.txt)

My Mac runs MacOS 10.13.3 and Java is build 1.8.0_101-b13

Thanks in advance for your help, best, Pietro

**Comment by qiemem** [comment]
Hi Pietro,

Thanks for trying out the extension! You need to copy the entire `py` folder over. Here's the complete contents for reference:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/28215/36953055-e9f6ab38-1fdc-11e8-99de-23e6646e3f6d.png">

More specifically, all the .jar and .py files are necessary.

**Comment by terna** [comment]
Many many thanks, Pietro

**Comment by qiemem** [comment]
Happy to help! Let me know if you run into any other problems!
